### PR TITLE
Enable Orchestrator for CI

### PR DESCRIPTION
**Pull request by Sloy**
This PR enables the Android Test Orchestator in the library. It should improve the stability of tests on CI.

### CODE REVIEW

**Comment by Sloy** [comment]
It worked!

**Comment by Sloy** [comment]
It takes a bit longer, but not too much. Do you agree we can merge this and see if it improves the flakiness?

**Comment by rocboronat** [comment]
Ooof course we can, @Sloy! Let's see what happens.

**Review by alorma — APPROVED** [review]

**Comment by rocboronat** [comment]
Let's see that automerge thing in action! 👍

**Review by rocboronat — APPROVED** [review]

**Pull request merged**
