### PR TITLE
Encourage collaborators to add tests written in Java

### PR DESCRIPTION
**Pull request by rocboronat**
This PR adds a subsection to the contributing section.

### CODE REVIEW

**Review by Sloy — APPROVED** [review]
👏

**Review by alorma — COMMENTED** [review]
Shouldn't we wait until #412 is merged so instead of this section we can link the contributing guide directly?

**Comment by rocboronat** [comment]
I wrote this thing first 😄 but yes, if everyone is ok with it, we could merge the other one, close this PR, and open a new one pointing to the contributions page in the readme. Everything is fine 😄

**Comment by Sloy** [comment]
Fine by me!

**Pull request merged**
