### PR TITLE
Create pull-request.yml - Not merge

### PR DESCRIPTION
**Pull request by alorma**

### CODE REVIEW

**Comment by rocboronat** [comment]
Just to know, what did you try to achieve?

**Comment by alorma** [comment]
Read this repo @rocboronat 

I've tried to add  an action to check all PR are "semantic", that is title contains "feat", "fix" or something like that

**Comment by rocboronat** [comment]
Which repo? The Barista one?

By the way, here's a vote against this stuff you're trying. Currently, we don't have any issue with having "non-semantic" PRs. The issue we have with the PRs is that we don't have time to invest in them 😅

**Comment by alorma** [comment]
Shame on me, not added the link:

https://github.com/amannn/action-semantic-pull-request

**Comment by alorma** [comment]
I know @rocboronat 

It was just a test for that feature in a non private repo ;)

**Comment by rocboronat** [comment]
Oh! Ok, totally understood... Perhaps we could try these things in another place...? A public personal repo would do the job I think. Just to keep Barista clean, you know...

Well, thanks for sharing the info!

**Comment by alorma** [comment]
I did in a personal one, but i needed an organization repo 😓

**Pull request closed without merging**
