### PR TITLE
Wrap the code that mocks the camera with a try-catch clause in the readme

### PR DESCRIPTION
**Pull request by rocboronat**
It happened to me that the code that performs something with the camera crashes, so the `release` is never called, so the next test fails because the `init` has been called twice without releasing it.

Totally open for discussion, of course! But as it's a piece of code that we're aiming people to copy-paste...

### CODE REVIEW

**Comment by alorma** [comment]
Wondering...

Maybe we can create a helper function, that does that?

Wrap code in a try catch and has a lambda to allow  any needed interactions

**Comment by Sloy** [comment]
I think the best / right approach is to do `Intents.init()` and `Intents.release()` in the `@Before` and `@After` in the test, and let JUnit handle it.

**Comment by rocboronat** [comment]
What do you think about doing it in the Barista rule, @Sloy?

**Comment by Sloy** [comment]
Dunno. That's actually what the IntentsTestRule does. Taking a quick look at the code, I don't see anything that could break. I don't know if there's any performance impact though.

But I don't really use the BaristaTestRule myself, so... go go go! 🥳

**Comment by Sloy** [comment]
PS: We need to talk about BaristaTestRule, the Espresso's ActivityTestRule is now deprecated in favor of ActivityScenario.

**Comment by rocboronat** [comment]
😱 🙀

**Comment by rocboronat** [comment]
Hey team! Is that an LGFM? 🤩

**Comment by rocboronat** [comment]
https://github.com/AdevintaSpain/Barista/issues/402 relates to this.

**Review by alorma — APPROVED** [review]

**Comment by rocboronat** [comment]
Thanks @alorma 😄

**Pull request merged**
