### PR TITLE
Day night rule 

### LINKED ISSUE #358: Pass the tests in both Day and Night mode
Sometimes, when you develop the Night Mode you put there some `if` clauses.

It would be great that Barista passes the tests in both Day and Night mode, magically, just to try all the paths the code has.

### PR DESCRIPTION
**Pull request by alorma**
Add `DayNightRule` so we can run tests on any of the `DayNight` modes, by default it launches on DAY and NIGHT modes

This PR fixes #358

untitled

### CODE REVIEW

**Comment by rocboronat** [comment]
Hey @alorma! Thanks a lot for this PR! You solved it faster than I wrote the issue, hehe!

Do you want me to introduce the rule in the README?

**Comment by alorma** [comment]
Sure @rocboronat!

**Comment by Sloy** [comment]
Wait, weren't you waiting for the readme?
tenor-64053998

**Comment by alorma** [comment]
No, @rocboronat will do in another PR (as he said)

**Pull request merged**
